REQUIRE, src/cg.jl, src/cg_lanczos.jl, src/cgne.jl, src/craig.jl, src/craigmr.jl, src/crmr.jl, test/test_cg.jl
Wasn't working with LBFGSOperator.
=> Use AbstractLinearOperator instead of LinearOperator

src/cg.jl, src/cg_lanczos.jl, src/cgls.jl, src/cgne.jl, src/craig.jl, src/crls.jl, src/crmr.jl, test/test_cg.jl, test/test_cg_lanczos.jl, test/test_cgls.jl, test/test_cgne.jl, test/test_craigmr.jl, test/test_crls.jl, test/test_crmr.jl, test/test_lsmr.jl, test/test_lsqr.jl, test/test_minres.jl
=> Return correctly on zero-residual solution

src/cg.jl, src/cg_lanczos.jl, src/cgls.jl, src/cgne.jl, src/craigmr.jl, src/crls.jl, src/crmr.jl, src/lsmr.jl, src/lsqr.jl, src/minres.jl, test/test_cg.jl, test/test_cg_lanczos.jl, test/test_cgls.jl, test/test_cgne.jl, test/test_craigmr.jl, test/test_crls.jl, test/test_crmr.jl, test/test_lsmr.jl, test/test_lsqr.jl, test/test_minres.jl
`r = 1.0*b` is the conversion to `Float64`, if the type is integer.
=> Accept integer types

src/cg.jl, src/cg_lanczos.jl, src/cgls.jl, src/cgne.jl, src/craig.jl, src/craigmr.jl, src/crls.jl, src/crmr.jl, src/krylov_aux.jl, src/lslq.jl, src/lsmr.jl, src/lsqr.jl, src/minres.jl
The main goals here are:
1. allow calls to iterative methods with different data types (e.g., Float16, BigFloat, etc.)
2. still permit efficient BLAS calls whenever possible (i.e., when the type is `<: BlasReal`)
For complex data, it doesn't seem that Julia calls `BLAS.cdot` or `BLAS.zdot` on those types. So it's probably ok to just call `dot`.
@abelsiqueira
=> Draft of dispatch on types

src/Krylov.jl, src/cg_lanczos.jl
Changed some   .+   .*   etc  to   +   *    .
=> Various dot operations for julia 0.6

src/cg.jl, src/cr.jl, src/krylov_aux.jl, test/test_aux.jl
Return the two roots for the function to_boundary
update cg.jl and cr.jl
=> Return the two roots in 'to_boundary'

src/crls.jl, src/krylov_aux.jl, test/test_aux.jl, test/test_crls.jl
- Add a boolean 'psd' to detect if A is positive semi-definite
- Check curvature in the direction p
- If zero curvature is encountered, choose the direction of best decrease between p and A'r
- Add test for A positive semi-definite
=> Add case of zero curvature in crls

src/symmlq.jl, src/variants.jl
=> preallocation for LinearOperator

src/cg.jl, src/cr.jl, test/test_cg.jl, test/test_cr.jl
=> preconditioned conjugate gradient and conjugate residual

src/crmr.jl, test/test_crmr.jl
=> Preconditioned CRMR

src/Krylov.jl, src/cgs.jl, src/diom.jl, src/dqgmres.jl, src/variants.jl, test/runtests.jl, test/test_cgs.jl, test/test_variants.jl
Classic version of CGS with right preconditioning.
=> An implementation of CGS

src/dqgmres.jl, test/test_alloc.jl
I found a proper way to update p_m when we use an unsafe_opeye. I build it from p_{m-mem}.
(lines 118-129)
=> Allocations tests for DQGMRES

src/diom.jl, test/test_alloc.jl
Same comment that I did for DQGMRES. The modification between lines 122 and 131 allows us to use an unsafe_opEye.
=> Allocations tests for DIOM

src/cr.jl, src/crls.jl, src/krylov_aux.jl, test/test_cr.jl
=> Modified CR for A non positive definite

src/cgls.jl, test/test_alloc.jl
@abelsiqueira 
I will open an other pull request after this one with multi-precision `CG` and `CGLS`.
=> Allocations tests for CGLS

src/Krylov.jl, src/cg.jl, src/cg_lanczos.jl, src/cgls.jl, src/cgne.jl, src/cgs.jl, src/cr.jl, src/craigmr.jl, src/diom.jl, src/dqgmres.jl, src/krylov_aux.jl, src/krylov_utils.jl, src/symmlq.jl, test/runtests.jl, test/test_mp.jl
@abelsiqueira 
I only updated `CG` and `CGLS` for the moment. Abel needs them in the near future.
=> Multi-precision CG and CGLS

test/runtests.jl, test/test_cg.jl, test/test_cg_lanczos.jl, test/test_cgls.jl, test/test_cgne.jl, test/test_cgs.jl, test/test_cr.jl, test/test_craig.jl, test/test_craigmr.jl, test/test_crls.jl, test/test_crmr.jl, test/test_diom.jl, test/test_dqgmres.jl, test/test_lslq.jl, test/test_lsmr.jl, test/test_lsqr.jl, test/test_minres.jl, test/test_symmlq.jl, test/test_utils.jl
I didn't remove random data used to build `InverseLBFGSOperator`.
I used a fixed seed instead.
fix #5
#81
=> Remove random tests

src/symmlq.jl, test/test_alloc.jl, test/test_symmlq.jl
=>  Allocations tests for SYMMLQ

src/craig.jl, src/craigmr.jl, test/test_craig.jl, test/test_craigmr.jl, test/test_lslq.jl, test/test_lsmr.jl, test/test_lsqr.jl, test/test_utils.jl
=> Generalized Golub Kahan Bidiagonalization

src/cg_lanczos.jl, src/cgne.jl, src/cgs.jl, src/cr.jl, src/craig.jl, src/craigmr.jl, src/crls.jl, src/crmr.jl, src/diom.jl, src/dqgmres.jl, src/lslq.jl, src/lsmr.jl, src/lsqr.jl, src/minres.jl, src/symmlq.jl, test/test_alloc.jl, test/test_cr.jl, test/test_minres.jl, test/test_mp.jl
The majority of the modifications are `1.0` that become `one(T)`, `0.0` that become `zero(T)` and small type stable stuff.
#103 
#126
=> Multiprecision support

appveyor.yml, test/get_div_grad.jl, test/test_utils.jl
I added Julia 1.3 in `appveyor.yml`.
I also moved eye function in `get_div_grad.jl` to keep some benchmarks working.
=> Update AppVeyor for Julia 1.3

src/diom.jl, test/get_div_grad.jl, test/test_bilq.jl, test/test_diom.jl, test/test_dqgmres.jl, test/test_qmr.jl, test/test_usymlq.jl, test/test_usymqr.jl, test/test_utils.jl
Example used  in the BiLQ article.
=> Poisson equation in polar coordinate

.travis.yml, Project.toml
First release supporting LinearOperators 1.0.
Preparing for Krylov 1.0.
=> Update dependencies, use Julia 1.3 on docs and coverage and release 0.4

.cirrus.yml, .travis.yml, Project.toml, appveyor.yml
Should we wait a last release with `LNLQ` and `USYMLQR` for Julia < 1.3 before we merge this pull request?
=> Drop Julia < 1.3 and add Julia 1.4

src/cg_lanczos.jl, src/cgne.jl, src/craigmr.jl, src/crls.jl, src/crmr.jl, src/lslq.jl, src/lsqr.jl, test/gen_lsq.jl, test/test_cgls.jl, test/test_crls.jl, test/test_lsmr.jl, test/test_lsqr.jl
=> Remove the last brave semicolons

.travis.yml, docs/make.jl, docs/src/api.md, docs/src/solvers.md, src/Krylov.jl, src/bilq.jl, src/bilqr.jl, src/cg.jl, src/cg_lanczos.jl, src/cgls.jl, src/cgne.jl, src/cgs.jl, src/cr.jl, src/craig.jl, src/craigmr.jl, src/crls.jl, src/crmr.jl, src/diom.jl, src/dqgmres.jl, src/lslq.jl, src/lsmr.jl, src/lsqr.jl, src/minres.jl, src/minres_qlp.jl, src/qmr.jl, src/symmlq.jl, src/trilqr.jl, src/usymlq.jl, src/usymqr.jl, src/variants.jl
=> Remove restriction on A, M and N parameters types

src/cg.jl, test/test_cg.jl, test/test_utils.jl
=> Add linesearch to CG

src/cg.jl, test/test_cg.jl
=> Check for inconsistency in CG

docs/make.jl, docs/src/gpu.md
=> Add a GPU section to the documentation

docs/Project.toml, docs/make.jl, docs/src/matrix-free.md
=> Add documentation about matrix-free operators

.zenodo.json, CITATION.bib, README.md
=> Update the DOI

Project.toml
=> Version 0.5.2

docs/src/gpu.md
=> Update the documentation about GPU support

src/variants.jl, test/test_alloc.jl
=> Replace identity operator modeled with UniformScaling by opEye

docs/src/matrix-free.md, docs/src/solvers.md, src/Krylov.jl, src/bicgstab.jl, src/variants.jl, test/runtests.jl, test/test_alloc.jl, test/test_bicgstab.jl, test/test_mp.jl, test/test_variants.jl
BICGSTAB(ℓ) is not relevant because it's quite expensive when ℓ increases and the combination of BiCG with restarted GMRES(ℓ) is worst than DQGMRES from my point of view.
I implemented the "basic" version of BICGSTAB, developed by Van Der Vorst.
=> An implementation of BICGSTAB

examples/test_cgs.jl
I updated IncompleteLU, it works like ILUZero now.
=> Update examples with IncompleteLU preconditioners

.github/workflows/Documentation.yml, docs/src/gpu.md
I updated some functions in CUDA.jl to make it working with Krylov methods (https://github.com/JuliaGPU/CUDA.jl/pull/540).
=> Add documentation about GPU features

src/bicgstab.jl, src/krylov_utils.jl, test/test_bicgstab.jl
I will update the other solvers if you're fine with this syntax.
https://ci.appveyor.com/project/dpo/krylov-jl/builds/36383369/job/he4b75f2pcfveayk#L80
=> [BICGSTAB] Add a frequency option for the verbose mode

Project.toml, docs/Project.toml, test/test_cr.jl
=> use LinearOperators 1.2.0

src/minres.jl, src/minres_qlp.jl, test/test_minres.jl, test/test_minres_qlp.jl
=> Fix the regularization in MINRES and MINRES-QLP

docs/src/gpu.md
=> Update the GPU documentation

src/lslq.jl, src/lsmr.jl, src/lsqr.jl, test/test_lslq.jl, test/test_lsmr.jl, test/test_lsqr.jl
+ Add the relations between SYMMLQ / LSLQ, CG / LSQR and MINRES / LSMR;
+ Add new tests for each method for regularized problems and saddle-point / sqd systems.
=> Update docstring of LSLQ, LSQR, LSMR

src/bicgstab.jl, src/bilq.jl, src/bilqr.jl, src/cg.jl, src/cg_lanczos.jl, src/cgls.jl, src/cgne.jl, src/cgs.jl, src/cr.jl, src/craig.jl, src/craigmr.jl, src/crls.jl, src/crmr.jl, src/diom.jl, src/dqgmres.jl, src/lslq.jl, src/lsmr.jl, src/lsqr.jl, src/minres.jl, src/minres_qlp.jl, src/qmr.jl, src/symmlq.jl, src/tricg.jl, src/trilqr.jl, src/trimr.jl, src/usymlq.jl, src/usymqr.jl
@dpo, do you have a publication associated to 
```
D. Orban,
The Projected Golub-Kahan Process for Constrained Linear Least-Squares Problems,
Cahier du GERAD G-2014-15, 2014.
```
?
=> Add references for all methods

src/variants.jl, test/test_variants.jl
@geoffroyleconte, I did a new release of `LinearOperators` (1.2.1). It should solve your issues with `Symmetric` matrices.
=> Test SymTridiagonal, Symmetric and Hermitian matrices

src/minres.jl
=> [MINRES] history option to not accumulate rNorms and ArNorms

test/test_alloc.jl
=> Wrapped allocations tests

.github/workflows/ci.yml
=> allow Github Actions failures with Julia nightly

src/krylov_utils.jl, test/test_aux.jl
=> Update kzeros and kones for SubArray type

src/krylov_solvers.jl
=> Add a new constructor for all KrylovSolvers

src/krylov_solvers.jl, src/minres.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in MINRES

src/diom.jl, src/dqgmres.jl, src/krylov_solvers.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in DIOM and DQGMRES

src/cr.jl, src/krylov_solvers.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in CR

src/cg_lanczos.jl, src/krylov_solvers.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! for CG_LANCZOS and CG_LANCZOS_SHIFT_SEQ

src/krylov_solvers.jl, src/symmlq.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in SYMMLQ

src/bicgstab.jl, src/cgs.jl, src/cr.jl, src/krylov_solvers.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in CGS and BICGSTAB

test/test_alloc.jl
We can reduce the tolerance thanks to #274.
=> Update tolerance for allocations tests

src/craig.jl, src/craigmr.jl, src/krylov_solvers.jl, src/lnlq.jl, src/variants.jl, test/test_alloc.jl, test/test_lnlq.jl
=> Use mul! in LNLQ, CRAIG and CRAIGMR

src/krylov_solvers.jl, src/lslq.jl, src/lsmr.jl, src/lsqr.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in LSLQ, LSQR and LSMR

src/cgne.jl, src/krylov_solvers.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in CGNE

src/minres.jl
After #304, I will add a section in the documentation in-place solvers.
=> Update the docstring of MINRES

src/cgls.jl, src/krylov_solvers.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in CGLS

src/crmr.jl, src/krylov_solvers.jl, src/variants.jl, test/test_alloc.jl
=> Use mul! in CRMR

src/lslq.jl, src/lsmr.jl, src/lsqr.jl
=> Fix dimensions of u and v in LSLQ, LSQR and LSMR

README.md, docs/src/index.md, docs/src/matrix-free.md
@dpo, I found a way to easily update badges.
It could be relevant for other JSO packages.
=> Add a badge for stable documentation

test/test_cgls.jl, test/test_cgne.jl, test/test_craig.jl, test/test_craigmr.jl, test/test_crls.jl, test/test_crmr.jl, test/test_lnlq.jl, test/test_lslq.jl, test/test_lsmr.jl, test/test_lsqr.jl, test/test_tricg.jl, test/test_trimr.jl, test/test_utils.jl
=> Test dimension of additional vectors

Project.toml
=> Release 0.7.2

src/diom.jl, src/dqgmres.jl, src/krylov_solvers.jl, test/runtests.jl, test/test_alloc.jl, test/test_inplace.jl
fix #331 
Test that we don't have side effects with in-place Krylov methods when multiple linear systems are solved with the same workspace.
=> Add tests for in-place solvers

test/test_lsqr.jl, test/test_usymlq.jl
With #332, some operators were replaced by matrices and some stopping conditions are triggered earlier with LSQR.
=> Update lsqr_tol for LSQR tests

src/krylov_solvers.jl, src/krylov_utils.jl
=> Remove Union{Nothing, S} in Krylov solvers

docs/make.jl, docs/src/factorization-free.md, docs/src/inplace.md, docs/src/matrix-free.md
=> Add documentation about in-place methods

.zenodo.json
Follows the recommendation of Abel (#205)
=> Fix .zenodo.json

src/krylov_stats.jl, test/runtests.jl, test/test_show.jl
This way we no longer have to redefine everything for the `show` functions of the Stats.
=> Generic show functions for stats

src/krylov_solvers.jl, src/usymlq.jl, src/usymqr.jl, test/test_alloc.jl
=> Use 5-argument mul! in USYMLQ

docs/src/api.md, src/krylov_solvers.jl, src/krylov_stats.jl, src/lslq.jl, test/test_alloc.jl, test/test_inplace.jl, test/test_lslq.jl, test/test_show.jl
Create a LSLQ Stats and add a 'transfer_to_lsqr' option similar to LNLQ to uniformize the output.
=> Conform lslq

src/krylov_solvers.jl, src/tricg.jl, test/test_alloc.jl
=> Use 5-arguments mul! in TRICG

.github/workflows/Documentation.yml, .github/workflows/ci.yml, .gitignore, README.md, benchmark/run_benchmarks.jl
These changes were made automatically, please check before merging.
=> [AUTO] Change master to main

src/krylov_solvers.jl, test/test_inplace.jl
=> Add generic solve! function

Project.toml
=> Release 0.7.4

src/krylov_solvers.jl, src/minres_qlp.jl, src/tricg.jl, src/trimr.jl, test/test_alloc.jl
=> Use 5-arguments mul! in TRIMR

src/lsqr.jl
=> zeros -> zero

src/cg_lanczos.jl
`shifts` should not be stored on GPU.
=> Improve GPU support for cg_lanczos

docs/src/inplace.md, src/krylov_solvers.jl
=> Add documentation for solve!

src/cg.jl, src/krylov_solvers.jl, test/test_alloc.jl
@amontoison toward 0-allocation cg :).
Let me know if you have any comments and I will keep going with the others, #361 .
=> Add in-place Stats in `cg`

Project.toml
=> Release 0.7.5

src/krylov_stats.jl, test/runtests.jl, test/test_solvers.jl, test/test_stats.jl, test/test_utils.jl
=> Add reset! function for KrylovStats

src/lslq.jl, src/lsmr.jl, src/lsqr.jl
=> Improve the docstring of LSLQ, LSQR and LSMR

src/bilqr.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for BiLQR

src/krylov_solvers.jl, src/trilqr.jl, test/test_alloc.jl
=> Add in-place stats for TriLQR

src/krylov_solvers.jl, src/qmr.jl, test/test_alloc.jl, test/test_qmr.jl
=> Add in-place stats for QMR

src/bilq.jl, src/krylov_solvers.jl, test/test_alloc.jl, test/test_bilq.jl
=> Add in-place stats for BiLQ

src/krylov_solvers.jl, src/tricg.jl, test/test_alloc.jl
=> Add in-place stats for TriCG

src/krylov_solvers.jl, src/usymlq.jl, test/test_alloc.jl
=> Add in-place stats for USYMLQ

src/krylov_solvers.jl, src/usymqr.jl, test/test_alloc.jl
=> Add in-place stats for USYMQR

src/krylov_solvers.jl, src/trimr.jl, test/test_alloc.jl
=> Add in-place stats for TriMR

src/craig.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for `craig`

src/bicgstab.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for BICGSTAB

src/cgs.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for CGS

src/krylov_solvers.jl, src/lsqr.jl, test/test_alloc.jl
#361 
Same as #393 , it will need a LsqrStats to have 0-allocation.
=> Add in-place stats for `lsqr`

src/diom.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for DIOM

src/krylov_solvers.jl, src/minres_qlp.jl, test/test_alloc.jl
=> Add in-place stats for MINRES-QLP

src/dqgmres.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for DQGMRES

src/cgls.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for `cgls`

src/crls.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for `crls`

src/cgne.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for `cgne`

src/crmr.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for `crmr`

src/craigmr.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> Add in-place stats for CRAIGMR

src/krylov_solvers.jl, src/lnlq.jl, test/test_alloc.jl
=> Add in-place stats for LNLQ

src/krylov_solvers.jl, src/symmlq.jl, test/test_alloc.jl
=> Add in-place stats for SYMMLQ

src/krylov_solvers.jl, src/lslq.jl, test/test_alloc.jl
=> Add in-place stats for LSLQ

src/cg_lanczos.jl, src/krylov_solvers.jl, test/test_alloc.jl
=> add in-place stats for CG-LANCZOS

docs/src/api.md, src/cg_lanczos.jl, src/krylov_solvers.jl, src/krylov_stats.jl, test/test_alloc.jl, test/test_cg_lanczos.jl, test/test_stats.jl
=> Add in-place stats for CG-LANCZOS with shifts

src/cg.jl, src/krylov_solvers.jl, test/test_cg.jl
=> Add restart in CG

src/krylov_solvers.jl, src/minres.jl, src/minres_qlp.jl, src/symmlq.jl, test/test_cg.jl, test/test_diom.jl, test/test_dqgmres.jl, test/test_fom.jl, test/test_gmres.jl, test/test_minres.jl, test/test_minres_qlp.jl, test/test_symmlq.jl, test/test_utils.jl
=> Add restart for SYMMLQ, MINRES and MINRES-QLP 

docs/Project.toml, docs/src/factorization-free.md, docs/src/gpu.md
=> Update the documentation for LinearOperators v2.0

docs/src/inplace.md, src/krylov_solvers.jl, test/test_solvers.jl
Related to #420.
It will be easier to add tests and update the documentation after #420.
=> Add functions nsolution, solution, statistics and issolved

Project.toml
Can be merged after #424 and #433.
=> Release 0.7.7

src/bilq.jl, src/qmr.jl, src/usymlq.jl, src/usymqr.jl
=> Add documentation about the argument c in BiLQ, QMR, USYMLQ and USYMQR

src/bicgstab.jl, src/cg.jl, src/cg_lanczos.jl, src/cgls.jl, src/cgne.jl, src/cgs.jl, src/cr.jl, src/craig.jl, src/craigmr.jl, src/crls.jl, src/crmr.jl, src/diom.jl, src/dqgmres.jl, src/fom.jl, src/gmres.jl, src/gpmr.jl, src/lnlq.jl, src/lslq.jl, src/lsmr.jl, src/lsqr.jl, src/minres.jl, src/minres_qlp.jl, src/symmlq.jl, src/tricg.jl, src/trimr.jl
=> Use === I instead of == I

src/krylov_solvers.jl, test/test_solvers.jl
I added a kwarg `show_stats` to display (or not) the KrylovStats of a KrylovSolver.
=> Update tests with krylov solvers

.github/workflows/Breakage.yml
=> Add RipQP in Breakage.yml

src/gmres.jl, src/gpmr.jl
I forgot to use the absolute value....
=> Hotfix for GMRES and GPMR

src/diom.jl, src/dqgmres.jl, src/fom.jl, src/gmres.jl, src/gpmr.jl
=> Add documentation about the memory kwarg in DIOM and DQGMRES

src/trilqr.jl
=> Fix the estimate of ‖Asₖ‖ in TriLQR

src/cr.jl
Hi, I have numerical issues with CR used with RipQP:
https://github.com/JuliaSmoothOptimizers/RipQP.jl/pull/139
I think this PR should fix my issues, but I can't be sure because the tests only fail with MacOS.
=> Fix sqrt CR

.github/workflows/Breakage.yml
=> Add a breakage test for LLSModels.jl

src/craig.jl, src/craigmr.jl, src/lnlq.jl, test/test_craig.jl, test/test_craigmr.jl, test/test_lnlq.jl
In the same spirit of #537 
I also fixed some errors in the docstrings.
=> Update docstrings of LNLQ, CRAIG, CRAIGMR

src/krylov_solvers.jl
Connected to https://github.com/JuliaSmoothOptimizers/LLSModels.jl/pull/35
=> Add default value `memory` in `KrylovSolver`

src/gpmr.jl, src/krylov_solvers.jl, test/test_gpmr.jl
I need #481 to add tests with complex numbers.
=> [GPMR] Support of complex numbers

src/usymlq.jl, test/test_usymlq.jl
After two days of debugging...
=> [USYMLQ] Support of complex numbers

src/minres.jl, test/test_minres.jl
The projection of hermitian `A` in the Krylov subspace is always a real tridiagonal matrix with the Lanczos process.
=> [MINRES] Support of complex numbers

src/crls.jl, test/test_crls.jl
Half of the tasks for #103 is done... (16 / 32 methods)
=> [CRLS] Support of complex numbers

src/tricg.jl, src/trimr.jl, test/test_alloc.jl
I have some issues with TriCG... :thinking: 
We have many allocations with the in-place method but only when we solve complex linear systems.
The good news is that the other 30 methods don't allocate with their in-place method when we solve complex linear systems !
=> Add allocation tests for complex linear systems

src/minres.jl
=> Add a generic docstring for minres and minres! functions

src/bicgstab.jl, src/bilq.jl, src/bilqr.jl, src/cgs.jl, src/krylov_solvers.jl, src/qmr.jl, src/trilqr.jl, src/usymlq.jl, src/usymqr.jl, test/test_solvers.jl, test/test_warm_start.jl
This PR adds the support of warm-start for the following methods:
- CGS
- BICGSTAB
- USYMLQ
- USYMQR
- BILQ
- QMR
- BILQR
- TRILQR
=> Warm-start feature

src/fom.jl, src/gmres.jl, test/test_fom.jl, test/test_gmres.jl
close #412
joint work with @geoffroyleconte
=> GMRES(k) and FOM(k)

src/bicgstab.jl, src/cg.jl, src/cg_lanczos.jl, src/cr.jl, src/diom.jl, src/dqgmres.jl, src/fom.jl, src/gmres.jl, src/minres.jl, src/minres_qlp.jl, src/qmr.jl, src/symmlq.jl, test/test_bicgstab.jl, test/test_cg.jl, test/test_cg_lanczos.jl, test/test_cr.jl, test/test_diom.jl, test/test_dqgmres.jl, test/test_fom.jl, test/test_gmres.jl, test/test_minres.jl, test/test_minres_qlp.jl, test/test_qmr.jl, test/test_symmlq.jl, test/test_utils.jl
- symmlq
- minres_qlp
- gmres
- dqgmres
- cg
- cg_lanczos
- cr
- bicgstab
- fom
- diom
- qmr
=> Add more callbacks

docs/make.jl, docs/src/callbacks.md
Once https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/590 is merged, I can rebase this PR to tackle https://github.com/JuliaSmoothOptimizers/Krylov.jl/issues/587.
=> Add documentation for callbacks

src/krylov_solvers.jl, src/krylov_stats.jl, src/lsmr.jl, test/test_stats.jl
Adding new LSMR stats in order to retrieve more information without additional cost.
=> New LSMR stats

Project.toml
Bumping krylov version to v0.8.3 in order to adapt to latest changes.
=> Bumping version to 0.8.3

src/krylov_utils.jl, test/test_aux.jl
It's an excellent idea @gdalle!
=> Use the multiple dispatch for ktypeof function

docs/src/solvers/as.md, docs/src/solvers/gsp.md, docs/src/solvers/ln.md, docs/src/solvers/ls.md, docs/src/solvers/sid.md, docs/src/solvers/sp_sqd.md, docs/src/solvers/spd.md, docs/src/solvers/unsymmetric.md
It will be easier to find the documentation of a specific method in the documentation.
=> [documentation] Add a section for each Krylov method

.github/workflows/CI_M1.yml, test/test_solvers.jl, test/test_usymqr.jl
#560 #244
@amontoison
Note that
> The Arm architecture provides high-performance and high-efficiency hardware support for floating-point operations in half-, single-, and double-precision arithmetic. Arm floating point technology is fully IEEE-754 compliant with full software library support.
(https://developer.arm.com/architectures/instruction-sets/floating-point)
I'll try to enable verbosity during those tests to find out what's going on.
=> comment out failing tests

src/krylov_solvers.jl
@paraynaud 
It should solve our issue with `CgSolver`.
=> [KrylovSolvers] inner constructors -> outer constructors

.buildkite/pipeline.yml, test/gpu/amd.jl, test/gpu/intel.jl, test/gpu/metal.jl, test/gpu/nvidia.jl, test/test_aux.jl
=> Use buildkite to test the GPU support

.buildkite/pipeline.yml, docs/make.jl, docs/src/gpu.md, test/gpu/amd.jl, test/gpu/intel.jl, test/gpu/metal.jl, test/gpu/nvidia.jl
#627 
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR630/gpu/
=> [documentation] update gpu.md

docs/src/preconditioners.md
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR633/preconditioners/#Examples
=> Add more examples with the preconditioners

Project.toml
=> Release 0.8.4

docs/src/callbacks.md
close #587 
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR629/callbacks/
https://discourse.julialang.org/t/how-to-extract-intermediate-results-from-gmres-of-krylov-jl/87019
=> [documentation] update callbacks.md

src/krylov_utils.jl
=> Add GPU support for to_boundary function

.github/workflows/Invalidations.yml
This is based on https://github.com/julia-actions/julia-invalidations.
Adding such checks came up in https://discourse.julialang.org/t/potential-performance-regressions-in-julia-1-8-for-special-un-precompiled-type-dispatches-and-how-to-fix-them/86359.
=> Add the workflow Invalidations.yml

Project.toml, test/aqua.jl, test/runtests.jl
Aqua.jl provides functions to run a few automatable checks for Julia packages:
- There are no method ambiguities.
- There are no undefined exports.
- There are no unbound type parameters.
- There are no stale dependencies listed in Project.toml.
- Check that test target of the root project Project.toml and test project (test/Project.toml) are consistent.
- Check that all external packages listed in deps have corresponding compat entry.
- Project.toml formatting is compatible with Pkg.jl output.
=> Use Aqua.jl in the tests

docs/src/gpu.md
@AntoninKns 
My PR in CUDA.jl was merged this morning.
=> Add the support of CuSparseMatrixCOO in gpu.md

src/bicgstab.jl, src/bilq.jl, src/bilqr.jl, src/cg.jl, src/cg_lanczos.jl, src/cg_lanczos_shift.jl, src/cr.jl, src/krylov_processes.jl, src/krylov_solvers.jl, src/minres.jl, src/minres_qlp.jl, src/qmr.jl, test/test_processes.jl, test/test_solvers.jl
=> Add m and n in all Krylov solvers

.github/workflows/Aqua.yml, .github/workflows/Documentation.yml, Project.toml, test/aqua.jl, test/runtests.jl
=> Create a Aqua workflow

docs/src/api.md, src/krylov_utils.jl, test/gpu/amd.jl, test/gpu/gpu.jl, test/gpu/intel.jl, test/gpu/metal.jl, test/gpu/nvidia.jl, test/test_aux.jl
=> Support a view of a matrix as a right-hand side b

docs/make.jl, docs/src/factorization-free.md, docs/src/storage.md
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR666/storage/
=> [documentation] Add a section storage requirements

docs/make.jl, docs/src/solvers/gsp.md, docs/src/solvers/sid.md, docs/src/solvers/sp_sqd.md, docs/src/solvers/spd.md, docs/src/solvers/unsymmetric.md, test/test_allocations.jl
I also renamed the section `Non-Hermitian linear systems` into `Non-Hermitian square linear systems`.
=> Use the same tolerance for all allocation tests

docs/make.jl, docs/src/warm-start.md
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR684/
=> [documentation] Remove the subsection restarted methods

paper/paper.bib, paper/paper.md
paper: https://github.com/JuliaSmoothOptimizers/Krylov.jl/suites/9499847733/artifacts/450669741
=> final pass over paper

docs/src/preconditioners.md
Thanks @lschork2 for your help with the Julia interface of BasicLU!
=> Add an example with BasicLU.jl in preconditioners.md

docs/src/gpu.md, test/gpu/nvidia.jl
close #709, close #710 
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR711/gpu/
=> [documentation] Update the page related to the GPU support

docs/src/gpu.md
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR714/gpu/
[JOSS review](https://github.com/openjournals/joss-reviews/issues/5187#issuecomment-1456271273)
=> [documentation] Update the GPU section

src/gpmr.jl, src/krylov_processes.jl
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR715/
=> Update the reference of the GPMR paper

.github/codecov.yml
@tmigot @abelsiqueira 
https://github.com/codecov/codecov-action/issues/554#issuecomment-1261250304
=> Add a threshold for codecov

paper/paper.md
=> Add Apple Accelerate for BLAS backends available with LBT

.github/workflows/Breakage.yml
=> Update Breakage.yml for LinearSolve.jl

paper/paper.md
@dpo 
The last comment to take into account is:
Line 80: I understand that you added this line for more clarification but it is still not quite clear in what way using BLAS affects your implementation. Is it something you can explain further?
=> [JOSS] Review comments of LeilaGhaffari

Project.toml, src/krylov_utils.jl
=> Release 0.9.3

CITATION.bib, CITATION.cff
Thanks for your help @abelsiqueira :+1:
=> CITATION.bib -> CITATION.cff

src/krylov_processes.jl, test/test_processes.jl
=> Add an option reorthogonalization for two processes

.cirrus.yml, docs/Project.toml, docs/make.jl
https://jso.dev/Krylov.jl/previews/PR811/
=> [documentation] Update Documenter.jl

Project.toml, src/craig.jl
=> [documentation] Add a reference for CRAIG

src/krylov_stats.jl, test/test_stats.jl
=> Add copyto! for KrylovStats

docs/src/gpu.md
=> [documentation] KrylovOperator -- optimized sparse products on NVIDIA and AMD GPUs

docs/make.jl, docs/src/preconditioners.md
https://github.com/tjdiamandis/RandomizedPreconditioners.jl/issues/6
=> [documentation] Add an example with RandomizedPreconditioners.jl

src/diom.jl, src/dqgmres.jl, src/fgmres.jl, src/fom.jl, src/gmres.jl, src/gpmr.jl, src/krylov_solve.jl
=> Use metaprogramming to generate more out-of-place methods

src/block_krylov_solvers.jl, src/krylov_solvers.jl
=> Specify that memory is an optional argument for some KrylovSolvers

src/car.jl, src/cg_lanczos.jl, src/cg_lanczos_shift.jl, src/cgls_lanczos_shift.jl, src/cr.jl, src/craig.jl, src/craigmr.jl, src/krylov_utils.jl, src/lnlq.jl, src/lslq.jl, src/lsmr.jl, src/lsqr.jl, src/minres_qlp.jl, src/tricg.jl, src/trimr.jl, test/test_trimr.jl
=> Add a function knorm_elliptic

docs/src/matrix_free.md
https://jso.dev/Krylov.jl/previews/PR912/matrix_free/
=> Improve the matrix-free example with FFT

.buildkite/pipeline.yml, docs/src/block_krylov.md, src/block_gmres.jl, src/block_krylov_solvers.jl, src/block_krylov_utils.jl, src/block_minres.jl
=> Use my new implementation of coytrito! in GPUArrays.jl

.github/workflows/ci.yml, test/test_cr.jl
https://julialang.slack.com/archives/C680MM7D4/p1737046305355719
=> [CI] Test Krylov.jl on Linux ARM

docs/Project.toml, docs/src/custom_workspaces.md
close #949 
cc @gdalle
https://jso.dev/Krylov.jl/previews/PR954/custom_workspaces/#Solving-saddle-point-systems-with-BlockArrays.jl-and-Krylov.jl
=> [documentation] Add an example with BlockArrays.jl

src/block_krylov_processes.jl, src/krylov_processes.jl, test/test_processes.jl
=> Add an option reorthogonalization in hermitian_lanczos

src/cg_lanczos.jl, src/cg_lanczos_shift.jl
=> [documentation] Update cg_lanczos.jl and cg_lanczos_shift.jl

src/minares.jl
@dpo Finally published online! :tada:
=> Update the reference of MinAres

.github/workflows/Invalidations.yml, Project.toml
=> Require Julia 1.10

.github/workflows/Breakage.yml
close #976 
@tmigot Could be relevant for you.
=> Update Breakage.yml for PRs from a fork

src/cg.jl
Requested in https://github.com/CliMA/Oceananigans.jl/pull/4387
=> Return a nice error if we detect the preconditioner is not SPD in CG

src/interface.jl
=> Remove aliases

docs/src/generic_interface.md, src/block_krylov_workspaces.jl, src/krylov_workspaces.jl, test/test_interface.jl
=> Add a function krylov_elapsed_time

docs/Project.toml, docs/src/custom_workspaces.md, docs/src/generic_interface.md, docs/src/inplace.md, src/workspace_accessors.jl, test/test_interface.jl
=> Polish the API for workspace accessors

Project.toml
=> Release 0.10

docs/src/custom_workspaces.md
We should be able to have a distributed Krylov solver for all implementations of `Krylov.jl`.  
Of course, it can target both CPU and any GPU architectures (NVIDIA, AMD, Intel). 😎
This could help justify an [INCITE](https://doeleadershipcomputing.org/) proposal. :metal:  :rocket: :muscle: 
--> [preview](https://jso.dev/Krylov.jl/previews/PR1003/custom_workspaces/#Distributed-Krylov-solvers-with-MPI.jl) <--
cc @michel2323
=> [documentation] Tutorial on distributed Krylov solvers using MPI.jl

src/minres.jl, test/test_minres.jl
Similar to https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/985
=> implementation Line Search with Negative Curvature Detection with direction for MINRES

Project.toml
Updated the package version in Project.toml from 0.10.1 to 0.10.2.
=> Bump version to 0.10.2
