- src/lsmr.jl
- src/lsqr.jl
The tolerance named `atol` is now called `axtol`. New tolerances `atol` and `rtol` play the role of absolute and relative tolerances on the optimality conditions.
> tolerances for optimization

- src/Krylov.jl
- src/diom.jl
- src/variants.jl
- test/runtests.jl
- test/test_diom.jl
- test/test_variants.jl
Little brother of `DQGMRES`.
Currently, the factorization is `H` is done without pivoting.
Like `DQGMRES`, we can avoid the storage of H and I found a way to preconditioned it too. 
This algorithm needs `2n + 1` vectors of `mem` coefficients.
> An implementation of DIOM

- src/crmr.jl
- test/test_crmr.jl
fixed #80 
`r` was pointed to the vector generated by `M * b`. This vector `r` wasn't allocated so when we did `Mq = M * q`, `r` was updated in the same time and pointed to the new vector generated by `M * q`.
We can do a `copy(M * b)` without problem, we need to allocate memory for `r`.
> Correct preconditioned CRMR

- src/cgne.jl
- test/test_alloc.jl
`A' * z` is allocated whereas it's not the case with `A.tprod(z)`
```julia
julia> @allocated A.tprod(p)
0
julia> @allocated A' * p
112
```
We had the same problem with `view`. A small allocation each step but at the end, around 150Mo is allocated only for that...
> Allocations tests for CGNE

- src/crls.jl
- src/lsmr.jl
- src/lsqr.jl
- test/test_alloc.jl
I replace `slightly` by `substantially` like you recommanded.
Modifications are similar to `LSMR` ones. Except 2 other allocations mistakes.
- A vector `d` was allocated at each iteration and was not needed.
- A vector `var` was used but it didn't seem to have any special utility.
> Allocations tests for LSQR

- src/cg.jl
```julia
n = 10^8
p = rand(n)
z = rand(n)
β = rand()
@time @kscal!(n, β, p)
0.092621 seconds (4 allocations: 160 bytes)
@time @kaxpy!(n, 1.0, z, p)
0.128674 seconds (4 allocations: 160 bytes)
@time @kaxpby!(n, 1.0, z, β, p)
0.147128 seconds (4 allocations: 160 bytes)
```
Benchmarks:
https://gist.github.com/amontoison/49edb603cf7d975b5e73b0e6f61fcf99
> Add a @kaxpby! operation in CG

- src/lslq.jl
- test/test_alloc.jl
I moved the transition to LSQR point at the end.
We could compute it only one time instead of updating it at each iteration.
> Allocations tests for LSLQ

- src/crls.jl
- test/test_alloc.jl
Even with the `(A * u, Aᵀ * v)` vectors preallocated and used as storage for `(s, q)`, I used more memory compared to `LSMR` with least square problems.
Is it normal or `CRLS` can be more optimized?
> Allocations tests for CRLS

- src/cg_lanczos.jl
- test/test_cg_lanczos.jl
#52 
I preconditioned those methods the same way that I did in `DQGMRES` in `DIOM`.  Lanczos orthogonalization is just a special case of Arnoldi orthogonalization, so we can add a preconditioner the same way.
However I don't really understood how we have the relations for updating `p` and `x`. I only know how to derived relations with a LU factorization of `Tₘ` and  it's quite different.  I suppose that we modified them with the help of the relation `σⱼ² (δⱼ - ωⱼ₋₁ / γⱼ₋₁) = pⱼᵀ A pⱼ`.
> Preconditioned CG_LANCZOS

- src/craig.jl
This PR
* closes #119 by implementing a stopping test based on the backward error
* implements a stopping test for ill-conditioned operators
* implements an option to transfer to the LSQR point at the end of the iterations
* removes old useless semicolons from the code.
It's easiest to examine each commit separately.
> CRAIG backward error

- src/krylov_aux.jl
- src/minres.jl
- test/test_alloc.jl
- test/test_minres.jl
- Commit `Test preconditioned MINRES` tests that without modification, preconditioned MINRES works.
- Commit `Allocations tests for MINRES` modified `copy(...)` into `@.` and add an allocation test for MINRES in `test_alloc`.
- Commit `Remove allocation for w in MINRES` computes wₖ from  wₖ₋₁ and wₖ₋₂ (w2 and w1) without allocation.
- Commit `Remove allocation for v in MINRES` uses the relation `M * r2 / β = v` to avoid the allocation of v. 
wₖ needs vₖ, so we need to compute it during the Lanczos process and before r2 contains `βₖ₊₁ M⁻¹ * vₖ₊₁` .
> Allocations tests for MINRES

- src/lslq.jl
- src/symmlq.jl
- test/test_alloc.jl
A little trick that I found for `USYMLQ`, `BiLQ` and `LNLQ`.
@dpo It could interested you, it's possible to avoid the allocation of `p` and only use `p̅` in your `USYMLQR`.
> Don't allocate w in SYMMLQ and LSLQ

- src/cg_lanczos.jl
- test/test_cg_lanczos.jl
fix #52 
Exactly the same modifications that I did for `CG_LANCZOS`.
Except that without preconditioner we have the following relation : `δhat = vₖᵀ(A + sᵢI)vₖ = vₖᵀAvₖ + sᵢ‖vₖ‖² = δ + sᵢ`.
But with a preconditioner M, `δhat = vₖᵀ(A + sᵢI)vₖ = vₖᵀAvₖ + sᵢ‖vₖ‖² = δ + ρ * sᵢ`.
‖vₖ‖_M = 1 but ρ = ‖vₖ‖² ≠ 1.
> Preconditioned CG_LANCZOS_SHIFT_SEQ

- Project.toml
We have to limit `LinearOperators` version, but also there are 69 commits since the last release.
Otherwise, we could choose an older point to make release 0.3.1.
> Version 0.3.1

- Project.toml
- docs/Project.toml
- src/bilq.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/diom.jl
- src/dqgmres.jl
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/minres_qlp.jl
- src/qmr.jl
- src/symmlq.jl
- src/usymlq.jl
- src/usymqr.jl
- test/test_alloc.jl
close #135 
I remove `A.tprod` but I don't understand something.
In the `REPL` with the following code :
```julia
using LinearOperators
M = rand(100,100)
x = rand(100)
A = PreallocatedLinearOperator(M)
A2 = A'
@allocated A2 * x
A3 = A'
@allocated A3 * x
```
Nothing is allocated when I compute `A3 * x` (cost of compilation of `*` method) whereas `Aᵀ * x` seems to be recompiled inside methods even if the method was compiled before.
And `Aᵀ = A'` is not allocating if the function has been "warm up"...
> Remove A.tprod

- src/Krylov.jl
- src/krylov_utils.jl
- src/symmlq.jl
- test/test_bilq.jl
- test/test_symmlq.jl
- test/test_usymlq.jl
- test/test_utils.jl
I modified SYMMLQ to be able to compute `x_lq` when `x_cg` doesn't exist.
`ζ = ζbar * c` is equal to `Inf` if `ζbar = Inf`  / `γbar = 0`.
The `η` variable has been introduce to solve this problem.
> SYMMLQ improvements

- docs/src/api.md
- docs/src/index.md
- docs/src/solvers.md
- src/Krylov.jl
- src/bilq.jl
- src/bilqr.jl
- src/krylov_utils.jl
- src/trilqr.jl
- src/usymlq.jl
- src/variants.jl
- test/get_div_grad.jl
- test/runtests.jl
- test/test_alloc.jl
- test/test_bilqr.jl
- test/test_mp.jl
- test/test_trilqr.jl
- test/test_utils.jl
- test/test_variants.jl
- BiLQR and TriLQR methods for solving adjoint systems Ax=b and Aᵀt = c
- ODE and PDE adjoint problems used as tests
- Generalized TriLQR for rectangular matrices
- Allows inconsistent dual systems in TriLQR (solved by USYMQR)
- Stop primal or dual system when it's solved and continues the other one
- Improve verbose mode and statuses in both methods
- Use BiLQ, QMR, USYMLQ and USYMQR residual norm estimates described in the BiLQR / TriLQR article
> BiLQR & TriLQR

- docs/make.jl
- docs/src/index.md
- src/bilq.jl
- src/bilqr.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/diom.jl
- src/dqgmres.jl
- src/krylov_aux.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/qmr.jl
- src/symmlq.jl
- src/trilqr.jl
- src/usymlq.jl
- src/usymqr.jl
Documenter automatically convert 1. 2. 3. into 1. 1. 1... I wasn't able to solve that so I used 1 - 2- 3- instead.
I also remarked that links to source weren't working. I solved this problem in the same time.
It's useful if a user want to see what parameters are needed by the Krylov solvers.
> hotfix documentation

- src/cg.jl
- src/cr.jl
- test/test_cg.jl
- test/test_cr.jl
fix #120 
The problem came from the initialization of `rNorm`.
> Suitable residual norm estimate in CR when a preconditioner is supplied

- docs/src/api.md
- src/Krylov.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/diom.jl
- src/dqgmres.jl
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/symmlq.jl
- src/variants.jl
- test/test_utils.jl
@abelsiqueira 
- Preconditioners are wrapped automatically in a LinearOperator
- `cgs`, `diom` and `dqgmres` don't allocate anymore a vector for products with transpose(A)
> Wrap automatically preconditioners in a LinearOperator

- src/minres_qlp.jl
- test/test_minres_qlp.jl
It was difficult to find memory for vₖ without allocating a new vector but I finally found it.
> Preconditioned MINRES-QLP

- src/craig.jl
- test/test_craig.jl
- test/test_utils.jl
I introduced a mistake in CRAIG with #104.
```julia
[  γ    λ ] [ c₂   s₂ ] = [  δ    0 ]
[  0    0 ] [ s₂  -c₂ ]   [  0    0 ]
c₂, s₂, δ = sym_givens(γ, λ)
```
Or it's γ that we want to zero out and not λ.
```julia
[  γ    λ ] [ -c₂   s₂ ] = [  0    δ ]
[  0    0 ] [  s₂   c₂ ]   [  0    0 ]
c₂, s₂, δ = sym_givens(λ, γ)
```
The commit fix this error, add a boolean parameter sqd + some tests for regularized problems and saddle-point / symmetric quasi-definite systems.
Docstrings have been updated too, it's `Ax + λs = b` that is solved when λ > 0 and not 
`Ax + √λs = b`.
> fix regularization in CRAIG

- src/krylov_aux.jl
close #215 
Related PRs : https://github.com/JuliaGPU/CUDA.jl/pull/419, https://github.com/JuliaGPU/CUDA.jl/pull/427 and https://github.com/JuliaLang/julia/pull/35124
> Update kref! for GPU support

- Project.toml
This new release fixes the left preconditioning of BiCGSTAB (#229)
> Release 0.5.5

- src/bicgstab.jl
- src/bilq.jl
- src/bilqr.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/diom.jl
- src/dqgmres.jl
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/minres_qlp.jl
- src/qmr.jl
- src/symmlq.jl
- src/tricg.jl
- src/trilqr.jl
- src/trimr.jl
- src/usymlq.jl
- src/usymqr.jl
That allows to read the default values of the arguments with the `help?>`  function, directly in Julia's REPL. 
*Note:* By default, `maxit` is set to `2 * length(b)` whenever `maxit=0`. Should we specify this value directly in the args?
> Add values of default arguments in docstrings

- .github/workflows/Documentation.yml
- .github/workflows/ci.yml
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions
@dpo 
-> GitHub Actions usage is free for public repositories and self-hosted runners.
> Add ci.yml for setting up GitHub Actions CI

- src/bicgstab.jl
- src/cgs.jl
- src/krylov_utils.jl
I only updated `BICGSTAB` and  `CGS` for the moment.
In the future, we should remove all occurrence of broadcast in the other solvers.
```julia
using Random, LinearAlgebra, CUDA, Krylov, BenchmarkTools
CUDA.allowscalar(false)
Random.seed!(0)
n = 2^12
A = Matrix(Symmetric(rand(n, n)))
cA = CuArray(A)
b = ones(n)
cb = CuArray(b)
@benchmark bicgstab($cA, $cb)
```
Before this pull request:
```julia
BenchmarkTools.Trial: 
memory estimate:  121.50 MiB
allocs estimate:  2654329
--------------
minimum time:     6.909 s (0.18% GC)
median time:      6.909 s (0.18% GC)
mean time:        6.909 s (0.18% GC)
maximum time:     6.909 s (0.18% GC)
--------------
samples:          1
evals/sample:     1
```
Now: 
```julia
BenchmarkTools.Trial: 
memory estimate:  6.25 MiB
allocs estimate:  368761 …
```
> Improve performance on GPU

- docs/src/gpu.md
CUDA.jl will change the syntax for triangular solves in the near future (https://github.com/JuliaGPU/CUDA.jl/pull/575).
I updated the documentation for the future release of CUDA and I also added what should be modified if we want to use ILU and Incomplete Cholesky preconditioners with `CuSparseMatrixCSR` type.
@frapac
> Update the documentation about preconditioners on GPU

- src/minres.jl
Hello, I found that MINRES was stopping early when I tested it with RipQP, and the residuals were not close to 0, because of the `test1` test.
I changed the test so that MINRES does not stop too early, however I still have to normalize `b` when solving `Ax=b`. I left the `test1` values displayed by the logger in case they are needed, but I can remove them.
> MINRES stopping conditions

- Project.toml
`~1.2` means `[1.2.0,1.3.0)`.
`1.2` means `[1.2.0,2.0.0)`.
Using `^` is the same as not using anything.
Ref.: https://pkgdocs.julialang.org/v1/compatibility/
> Don't use ~1.2 in compat

- src/craig.jl
- src/craigmr.jl
- src/lnlq.jl
Fix #321 
@tmigot
I need to add new tests.
We only test the preconditioners M and N in these methods with square matrices A.
> Fix dimensions of u and v in LNLQ, CRAIG and CRAIGMR

- Project.toml
- src/Krylov.jl
- src/bicgstab.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/diom.jl
- src/dqgmres.jl
- src/lnlq.jl
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/minres_qlp.jl
- src/symmlq.jl
- src/tricg.jl
- src/trimr.jl
@geoffroyleconte @abelsiqueira @dpo
Vectors inside KrylovSolvers used for the preconditioners or the regularization are `Union{S, Nothing}`.
Sometimes 16 extra bits are required for type inference.
To help Julia I added some `::S`.
> Update Project.toml and remove dependencies of LinearOperators.jl

- src/bilq.jl
- src/krylov_solvers.jl
- src/qmr.jl
- test/test_alloc.jl
- test/test_show.jl
> Use 5-arguments mul! in BILQ and QMR

- src/krylov_stats.jl
- src/lnlq.jl
- test/test_alloc.jl
- test/test_lnlq.jl
- test/test_show.jl
This would fix Issue #265 .
The modification is heavily inspired by the Matlab implementation: [https://github.com/restrin/LinearSystemSolvers/blob/master/LNLQ/lnlq.m](https://github.com/restrin/LinearSystemSolvers/blob/master/LNLQ/lnlq.m).
A couple of comments:
- We use the CRAIG-bound when `transfer_to_craig` is set as true.
- Due to numerical issues, the `sqrt` in the bound might not be defined. When this happens, there is a boolean `complex_error_bnd` set as `true` and we stop computing this bound.
- The extra allocations are due to the use of `LNLQStats` instead of `SimpleStats`.
> Estimate of the error in LNLQ

- src/krylov_stats.jl
- src/lslq.jl
- test/test_alloc.jl
- test/test_lslq.jl
- test/test_show.jl
Add a boolean when there is a `DomainError` in the computation of the upper bound instead of having an error.
> Add a boolean for error in bound computation for LSLQ

- src/tricg.jl
- src/trimr.jl
The article about TriCG and TriMR is published online : https://epubs.siam.org/doi/abs/10.1137/20M1363030
> Update the reference of TriCG and TriMR

- src/krylov_solvers.jl
- src/lsmr.jl
- test/test_alloc.jl
#361 
This one is not completely with 0 allocations as we will need a LsmrSolver I think for the `err_vec`. I suggest we fix this in a separate PR.
> Add in-place stats for `lsmr`

- src/diom.jl
- src/dqgmres.jl
- src/fom.jl
- src/gmres.jl
- src/krylov_solvers.jl
- test/test_alloc.jl
close #170 
The subproblem of DIOM and FOM is different when pivoting is enable and we cannot compute the residual norm.
I understand now why it's was only mentioned in DIOM article...
> Remove pivoting option in DIOM and FOM

- src/krylov_stats.jl
- test/test_alloc.jl
- test/test_stats.jl
@tmigot 
Julia cannot inferred the type of `statfield = getfield(stats, field)` in the generic `reset!` function.
> Remove allocations with reset! function

- src/krylov_stats.jl
Solving the issue raised in #417 .
However, I don't see how to include the `LanczosShift` as adding
```
@eval function empty_field!(stats :: $T, i, ::Type{Vector{Vec}}) where {S, Vec<:AbstractVector}
statfield = getfield(stats, i)
for vec in statfield
empty!(vec)
end
end
```
seems to allocate (the type of `statfield` being problematic apparently...).
> Generic `reset!` function

- src/krylov_solvers.jl
- test/test_solvers.jl
The suggested `show` would print:
```
julia> cg_solver
CgSolver{Float64, Vector{Float64}}:
Δx: Vector{Float64} of length 0
x: Vector{Float64} of length 10
r: Vector{Float64} of length 10
p: Vector{Float64} of length 10
Ap: Vector{Float64} of length 10
z: Vector{Float64} of length 0
Simple stats
solved: false
inconsistent: false
residuals: []
Aresiduals: []
status: unknown
```
@amontoison if it looks good for you I will add the unit tests for the coverage.
> `show` function for KrylovSolvers

- docs/Project.toml
AMD.jl is not used by the examples.
> Remove AMD.jl -- docs/Project.toml

- docs/Project.toml
- docs/src/examples.md
- docs/src/factorization-free.md
- docs/src/gpu.md
- docs/src/tips.md
Thanks to @geoffroyleconte, it's now possible to define a 3-args mul! neatly.
This pull request can be merged after the hotfix https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/pull/203 dedicated to the BlockDIagonalOperator and a minor release 2.2.1 of LinearOperators.jl.
> Update the linear operators in the documentation

- src/bicgstab.jl
- src/bilq.jl
- src/bilqr.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crmr.jl
- src/diom.jl
- src/dqgmres.jl
- src/fom.jl
- src/gmres.jl
- src/lnlq.jl
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/minres_qlp.jl
- src/qmr.jl
- src/symmlq.jl
- src/tricg.jl
- src/trilqr.jl
- src/trimr.jl
- src/usymlq.jl
- src/usymqr.jl
close #448 
-> Five references don't have a DOI (3 thesis / 1 ETNA paper and a technical report)
* J. E. Craig, *Iterations Procedures for Simultaneous Equations*, Ph.D. Thesis, Department of Electrical Engineering, MIT, 1954.
* G. L.G. Sleijpen and D. R. Fokkema, *BiCGstab(ℓ) for linear equations involving unsymmetric matrices with complex spectrum*, Electronic Transactions on Numerical Analysis, 1, pp. 11--32, 1993.
* S.-C. T. Choi, *Iterative methods for singular linear equations and least-squares problems*, Ph.D. thesis, ICME, Stanford University, 2006.
* D. C.-L. Fong, *Minimum-Residual Methods for Sparse, Least-Squares using Golubg-Kahan Bidiagonalization*, Ph.D. Thesis, Stanford University, 2011.
* D. Orban, *The Projected Golub-Kahan Process for Constrained Linear Least-Squares …
> Update the references -- DOI

- src/lsqr.jl
- test/test_solvers.jl
The returned status on the zero residual wasn't updated during the iteration process.
> Update `zero_resid` in `lsqr`

- src/lslq.jl
- src/lsmr.jl
- test/test_solvers.jl
After #469 , I checked the other methods and found these two with the same issue.
> fix `zero_resid` in `lslq` and `lsmr`

- src/craig.jl
- src/craigmr.jl
- src/krylov_solvers.jl
- src/lnlq.jl
- test/test_alloc.jl
- test/test_craigmr.jl
- test/test_solvers.jl
I found a way to update x without computing Aᵀy, even if λ > 0 in CRAIGMR! With this pull request, #171 and #128 everything is now generalized for saddle-point / SQD systems.
> Add regularization in CRAIGMR

- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/symmlq.jl
To harmonize the verbose mode of the different Krylov methods, I replaced in @dpo implementations the number of matrix-vector products by the number of iterations.
Even if the number of matrix-vector products is a more relevant metric, our stopping conditions are based on the maximum number of iterations (`itmax`) and it's easier for the user to understand what is the current iteration now.
We could also display the number of matrix-vector products but I don't see in which context it can be useful. If we want to count them for a paper, we should distinguish the matvec products between `A`, `Aᵀ` and potentially `B`. In this case we should use `LinearOperators` to do that correctly.
> harmonize verbose mode

- src/gpmr.jl
- test/test_gpmr.jl
- test/test_utils.jl
close #466 
@dpo 
Our orthogonal Hessenberg process continues if `hₖ₊₁.ₖ = 0` or `fₖ₊₁.ₖ = 0`.
We just need to not normalize `vₖ₊₁` or `uₖ₊₁` if we encounter these cases.
In our article, we propose to handle breakdowns theoretically like this
```
"""In case of breakdown, which happens if Auₖ ∈ Span{v₁ , ... , vₖ} or Bvₖ ∈ Span{u₁ , ... , uₖ},
we choose an arbitrary unit vₖ₊₁ ⊥ Span{v₁, ... , vₖ} or uₖ₊₁ ⊥ Span{u₁, ... , uₖ}
and set βₖ₊₁ = 0 or γₖ₊₁ = 0, respectively."""
```
in the proof of the orthogonal Hessenberg process (GPMR paper).
For this reason,  the process should be stopped after `p := min{m,n}` iterations.
But numerically, it also works to set `βₖ₊₁ = vₖ₊₁ = 0` if `Auₖ ∈ Span{v₁ , ... , vₖ}` or `γₖ₊₁ = uₖ₊₁ = 0` if `Bvₖ ∈ Span{u₁ , ... , uₖ}`.
We can continue the process until …
> Hotfix for breakdowns in GPMR

- src/krylov_utils.jl
The function `dot(x,y)` with complex vectors `x` and `y` returns a complex number but we often use it to compute the square of a norm ([1](https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/513/files#diff-1c53f5530b6a52bd5ac553b00751b0edec2a0247374486956b59a1b1de58a436R237),[2](https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/513/files#diff-1c53f5530b6a52bd5ac553b00751b0edec2a0247374486956b59a1b1de58a436R246)) or p'Ap with hermitian positive definite matrices `A` ([3](https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/490/files#diff-95df883ef1fb65ddd8cf36cf67c8360830ddc4236f149c591f604a50a55852d9R121)).
In these cases, the result of the dot product is a complex number with an imaginary part equals to 0.
For all methods, I added `real(dot(x,y))` when it was needed but It …
> Add a new macro @kdotr

- src/lslq.jl
close #516 
close #472 
@tmigot I solved the issue with the estimate of ‖rₖ‖ in LSLQ.
A variable `ss` was never updated and `ζ` was used instead of `ζold`.
> Fix the estimate of ‖rₖ‖ in LSLQ

- docs/src/examples.md
- docs/src/factorization-free.md
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- test/test_lslq.jl
- test/test_lsmr.jl
- test/test_lsqr.jl
@geoffroyleconte 
The `sqd` parameter was only used to set `λ=1`.
I propose to use `λ` parameter directly.
> Update docstrings of LSLQ, LSQR, LSMR

- src/bicgstab.jl
- src/gmres.jl
- src/krylov_solvers.jl
- src/qmr.jl
- test/test_bicgstab.jl
- test/test_gmres.jl
- test/test_qmr.jl
- test/test_utils.jl
This PR adds complex support for the following solvers:
* `qmr`
* `gmres`
* `bicgstab`
The intent is to show what it would take to start to address #103 , namely, the following for the remaining solvers:
* Separating the type of the history `T` (as in `SimpleStats{T}`) from the type parameter of the eltype the solver expects. This involves adding an additional solver type parameter
* Minor adjustments to the solver to respect solving over complex matrices.
As part of this PR, the type restrictions in `krylov_utils.jl` were relaxed, and meaningful tests for complex matrices were added.
> [QMR / GMRES / BICGSTAB] Support of complex numbers

- src/krylov_solvers.jl
- src/minres.jl
- test/test_minres.jl
- test/test_solvers.jl
I found the use of the restart option not convenient to write generic code. Also the fact that the `restart` parameter was in the arguments of the function was misleading because it was not possible to restart `minres` (the not in-place version) (correct me if I'm wrong).
I added a function `warm_start!(solver, x0)` that is used to tell MINRES to solve the problem from x0. 
`MinresSolver` has now an attribute `restart` set to false by default. When using `warm_start!`, it is set to true. After `minres!` is called, it is set to false again.
If we agree to merge with, we could do the same for all other Krylov solvers by adding a method to the `warm_start!` function.
> [MINRES] Move restart option to MinresSolver

- docs/src/reference.md
- src/krylov_utils.jl
@dpo, Documenter.jl is not able to display docstrings of function defined as:
```
"""
My function foo
"""
function foo end
```
if we have duplicates.
I didn't find how to solve this problem with removing the `@autodocs` block.
The docstring of `minres`, `gmres`, ... are not display anymore.
> Fix the documentation

- src/diom.jl
- src/dqgmres.jl
- test/test_diom.jl
- test/test_dqgmres.jl
@geoffroyleconte 
I added partial reorthogonalization in DIOM and DQGMRES.
You should try DIOM and DQGMRES with `memory=2` and `reorthogonalization=true`.
You will have a more stable version of `CG` and `MINRES` for the same storage requierements.
> Add partial reorthogonalization in DIOM and DQGMRES

- src/krylov_utils.jl
close #573 
It also concerns #605
> Update ktypeof function to support BlockArrays and FillArrays

- docs/make.jl
- docs/src/inplace.md
- docs/src/matrix-free.md
- src/bicgstab.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cg_lanczos_shift.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/diom.jl
- src/dqgmres.jl
- src/fom.jl
- src/gmres.jl
- src/gpmr.jl
- src/krylov_utils.jl
- src/lnlq.jl
- src/lslq.jl
- src/lsmr.jl
- src/lsqr.jl
- src/minres.jl
- src/minres_qlp.jl
- src/symmlq.jl
- src/tricg.jl
- src/trimr.jl
We should be able to switch between `mul!̀` and `ldiv!` if we add a boolean argument to all Krylov methods that support preconditioners. This parameter will be the last argument of `kmuldiv!` function.
> Replace mul! by mulorldiv! for preconditioners

- src/cr.jl
- test/test_cr.jl
close #598 
The estimate of ||r|| is not numerically stable (https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/src/cr.jl#L284). We should compute the residual norm explicitly when it's possible.
We have a catastrophic cancellation because we are subtracting two nearby numbers when we almost converge.
> Improve rNorm estimate in CR

- src/bilq.jl
I don't know if I should add the publisher `Springer` for this reference.
`Numerical Analysis` is a book and not a journal paper.
> Add a reference to BiCG paper

- src/krylov_solvers.jl
- src/krylov_stats.jl
- src/minres.jl
- test/test_solvers.jl
@dpo @tmigot 
I modified the `show` function for the Krylov solvers.
It displays `nrows`, `ncols` AND the `storage` used by the solver!!!
Maybe we should say `unallocated` for the size of empty vectors instead of `0` byte.
What do you think? 
```julia
using SuiteSparseMatrixCollection, MatrixMarket, Krylov
ssmc = ssmc_db()
matrix_name = "pre2"
matrix = ssmc_matrices(ssmc, "", matrix_name)
paths = fetch_ssmc(matrix, format="MM")
M = MatrixMarket.mmread(joinpath(paths[1], matrix_name * ".mtx"))
bilq_solver = BilqSolver(size(M)..., Vector{Float64})
bicgstab_solver = BicgstabSolver(size(M)..., Vector{Float64})
matrix_name = "nlpkkt200"
matrix = ssmc_matrices(ssmc, "", matrix_name)
paths = fetch_ssmc(matrix, format="MM")
M = MatrixMarket.mmread(joinpath(paths[1], matrix_name * ".mtx")) …
```
> Better display of Krylov solvers

- test/test_allocations.jl
- Take into account that some vectors are real in the workspace (`KrylovSolver`) when we solve complex linear systems;
- The functions that return the number of bits allocated by a method is now generic for matrices of size `m x n`;
- Test with `Float32` and `ComplexF32`.
> Improve allocation tests

- src/bicgstab.jl
- src/bilq.jl
- src/bilqr.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgs.jl
- src/cr.jl
- src/diom.jl
- src/dqgmres.jl
- src/fgmres.jl
- src/fom.jl
- src/gmres.jl
- src/gpmr.jl
- src/minres.jl
- src/minres_qlp.jl
- src/qmr.jl
- src/symmlq.jl
- src/tricg.jl
- src/trilqr.jl
- src/trimr.jl
- src/usymlq.jl
- src/usymqr.jl
Is `⦗...⦘` well displayed on Windows and Mac?
I don't want to use`[]` for optional arguments but I hope that all OS have a font for this unicode character.
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR656/solvers/spd/#CG
> Add optional argument(s) in the docstrings

- src/lnlq.jl
- test/test_lnlq.jl
I also fixed a bug. `solved_lq` must be always updated if `σₑₛₜ > 0`.
> [LNLQ] Use utolx and utoly instead of etolx and etoly

- src/krylov_processes.jl
- test/test_processes.jl
- The upper Hessenberg matrices are now stored as dense matrices (`Arnoldi` and `montoison_orban` processes).
It's less expensive in storage for `Float32`, `Float64`, `ComplexF32` and the difference is quite small for `ComplexF64`.
- For the four other processes, I replaced all `M[i,j]` where `M` is the projection of `A` in the Krylov subspace (`T`, `Tᴴ` or `L` variables) by `nzval[k]` where `k` is the index of `M[i,j]` in `M.nzval`.
It will be a little bit faster because Julia won't need to compute the index `k` and check if `M[i,j]` is already allocated. 
**Note:** I don't want to store a sparse matrix `A` with the type `SparseMatrixCSC{T,Int32}` instead of `SparseMatrixCSC{T,Int64}` because `A \ b` is not working for this type.
We must use `Int64` to dispatch to `SuiteSparse` routines.
> Improve Krylov processes

- docs/src/solvers/ln.md
- docs/src/solvers/ls.md
- docs/src/solvers/unsymmetric.md
- src/usymlq.jl
- src/usymqr.jl
> Change the category of USYMLQ and USYMQR

- paper/paper.md
@amontoison Les exemples Newton et Gauss-Newton sont très semblables. Le GN est un peu plus intéressant puisqu'il utilise un problème rectangulaire. Je n'insiste pas pour en enlever un. On peut y aller et voir ce que disent les arbitres.
> pass over paper

- .buildkite/pipeline.yml
- docs/src/gpu.md
- src/minres.jl
- src/minres_qlp.jl
- test/gpu/amd.jl
- test/gpu/intel.jl
- test/gpu/metal.jl
- test/gpu/nvidia.jl
A new release of `GPUArrays.jl` is available.
My generic fallbacks for `dot` and `reflect!` should work now.
It will solve some issues with Intel / Apple M1 GPUs.
> Add new tests for GPUs

- paper/paper.md
For the [JOSS review](https://github.com/openjournals/joss-reviews/issues/5187#issuecomment-1456271273) of Krylov.jl
> Improve the JOSS paper with the comments of prj-

- docs/src/gpu.md
- test/gpu/nvidia.jl
`ldiv!(y, P, x)` returns a vector with `NaN` numbers if `y` has a `NaN`.
I thought that it was not a problem to have some `NaN` in `y` because the vector is overwritten by the result of `P \ x`.
It works fine on CPU but `NaN` is probably represented differently on GPU. I suspect that they use a pointer to a "CUDA" void.
> [documentation] Use CUDA.zeros instead of similar

- .buildkite/pipeline.yml
- docs/src/gpu.md
When I updated CUDA.jl for CUDA Toolkit 12.0, I found a few bugs in the new CUDA Toolkit.
I reported the issues to NVIDIA and my contact at NVIDIA explained that the fixes will be in the release 12.1.1.
> Test Krylov.jl with CUDA 12.1.1

- docs/src/processes.md
- src/krylov_processes.jl
- test/gpu/gpu.jl
- test/test_processes.jl
https://jso.dev/Krylov.jl/previews/PR813/processes/
> Update Krylov processes to return more arguments

- docs/src/block_krylov.md
- src/block_krylov_utils.jl
https://jso.dev/Krylov.jl/previews/PR844
> Add comments about using block-GMRES on GPUs

- .buildkite/pipeline.yml
- src/block_gmres.jl
- test/cpu/linear_operators.jl
close #861 
Thanks @gdalle for your PR in `LinearOperators.jl`!
> Add tests with LinearOperators.jl

- docs/src/preconditioners.md
- src/bilq.jl
- src/krylov_solvers.jl
- src/qmr.jl
- src/usymlq.jl
- src/usymqr.jl
- test/test_bicgstab.jl
- test/test_bilq.jl
- test/test_cgs.jl
- test/test_qmr.jl
> Support preconditioners in BiLQ and QMR

- README.md
Fixed the download count badge using https://juliapkgstats.com/.
This PR:
- Replaces the broken badge with a new badge that uses the new API
Please review and provide any feedback. Thanks for considering this PR!
> Fix download count badge

- docs/Project.toml
- docs/src/matrix_free.md
@michel2323 @frapac 
https://jso.dev/Krylov.jl/previews/PR883/matrix_free/#Example-3:-Solving-the-Poisson-equation-with-FFT-and-IFFT
> [documentation] Add a matrix-free example with FFTW.jl

- src/bicgstab.jl
- src/bilq.jl
- src/bilqr.jl
- src/block_gmres.jl
- src/block_krylov_solvers.jl
- src/car.jl
- src/cg.jl
- src/cg_lanczos.jl
- src/cgls.jl
- src/cgne.jl
- src/cgs.jl
- src/cr.jl
- src/craig.jl
- src/craigmr.jl
- src/crls.jl
- src/crmr.jl
- src/krylov_solve.jl
- src/krylov_solvers.jl
- src/lnlq.jl
- src/minares.jl
- src/minres_qlp.jl
- src/qmr.jl
- src/tricg.jl
- src/trilqr.jl
- src/trimr.jl
- src/usymlq.jl
- src/usymqr.jl
All Krylov methods are concerned but I only want to use it for `block_gmres` now.
I want to check the impact on precompilation time for the other methods.
Update: No performance reduction on non-Block Krylov methods. :+1:
> Use metaprogramming to generate out-of-place methods

- src/block_gmres.jl
- src/block_krylov_solvers.jl
- src/block_krylov_utils.jl
> Fix block_gmres on GPUs

- docs/src/matrix_free.md
Replace #910 such that we can build a preview of the documentation.
cc @michel2323
-> https://jso.dev/Krylov.jl/previews/PR911/matrix_free/#Example-with-discretized-PDE
> Matrix-free example example with a PDE

- src/krylov_stats.jl
#876 
cc @gdalle
https://jso.dev/Krylov.jl/previews/PR917
> [documentation] Improve the docstring of SimpleStats

- src/krylov_solve.jl
> [documentation] Add comments in krylov_solve.jl

- src/bicgstab.jl
> [documentation] Add a link for the paper of BiCGstab(ℓ)

- src/krylov_utils.jl
`rmul!` will dispatch to BLAS routines on GPUs:
- https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cublas/linalg.jl#L9
- https://github.com/JuliaGPU/AMDGPU.jl/blob/master/src/blas/highlevel.jl#L7
- https://github.com/JuliaGPU/oneAPI.jl/blob/master/lib/mkl/linalg.jl#L14
It will be also faster for CPU types, the code is
```julia
function rmul!(X::AbstractArray, s::Number)
@simd for I in eachindex(X)
@inbounds X[I] *= s
end
X
end
```
in the source code of Julia (`julia/stdlib/v1.11/LinearAlgebra/src/generic.jl`).
> Use rmul! instead of broadcast for kscal!

- src/krylov_utils.jl
- Use `kdot` and `kdotr` instead of `dot`.
- Fix an error if `to_boundary` is used with complex numbers.
> Fix to_boundary for complex numbers

- docs/src/api.md
- docs/src/block_krylov.md
- docs/src/block_processes.md
- docs/src/gpu.md
- docs/src/preconditioners.md
- src/Krylov.jl
- src/block_gmres.jl
- src/block_krylov_processes.jl
- src/block_krylov_solvers.jl
- src/block_minres.jl
- src/krylov_processes.jl
- src/krylov_solve.jl
- src/usymlq.jl
- src/usymqr.jl
- test/gpu/amd.jl
- test/gpu/gpu.jl
- test/gpu/intel.jl
- test/gpu/metal.jl
- test/gpu/nvidia.jl
> Add an implementation of BLOCK-MINRES

- src/gpmr.jl
- src/tricg.jl
- src/trimr.jl
- test/test_gpmr.jl
- test/test_tricg.jl
- test/test_trimr.jl
- test/test_utils.jl
@dpo 
The PR could interest you, `b` or `c` can be zero now in `TriCG`, `TriMR` and `GPMR`.
We didn't know that we wrote the papers on these methods.
`USYMLQR` is probably also concerned.
I also started to proofread iTriCG and iTriMR, and it seems that we can be smarter in how we handle the breakdown in SSY and MO processes.  
From what they explain in the paper, SSY can be simplified into Golub-Kahan if `b = 0` or `c = 0`.
I need to check if it’s correct or not; I have some doubts.
> Upgrade TriCG, TriMR and GPMR

- src/fgmres.jl
- src/fom.jl
- src/gmres.jl
- src/gpmr.jl
> Use similar for dynamic allocations

- src/cr.jl
- test/test_cr.jl
- test/test_utils.jl
This PR fixes an issue in the Conjugate Residual (CR) implementation (in `src/cr.jl`) where, on the first iteration (`iter == 0`), if the computed curvature is non-positive (i.e. either zero or negative), the algorithm may return without updating the iterate—even though we have  
$$b = -\nabla f(x_k) \neq 0.$$
To address this, when line search is enabled and a non-positive curvature (zero or negative) is detected at iteration 0, we now explicitly update the iterate by performing
```julia
x .= b
```
This change guarantees that the method behaves consistently by setting `x` appropriately when curvature information is either zero or negative during the first iteration.
---
**Changes Made:**
1. **First Iteration Check (iter == 0):**  
- When either zero or negative curvature is detected (i.e. …
> CR: Update iterate on first iteration for negative curvature with line search and when zero curvature is detected

- Project.toml
- src/block_krylov_solvers.jl
- src/krylov_solvers.jl
- src/krylov_stats.jl
- src/minres.jl
- test/test_minres.jl
- test/test_stats.jl
**Description:**  
This pull request introduces a new line search routine to the MINRES algorithm, incorporating negative curvature detection as outlined in Algorithm 1 of:
>Liu, Yang & Roosta, Fred. (2022). *A Newton-MR algorithm with complexity guarantees for nonconvex smooth unconstrained optimization*. [[10.48550/arXiv.2208.07095](https://doi.org/10.48550/arXiv.2208.07095)](https://doi.org/10.48550/arXiv.2208.07095)
**Key Changes:**  
- **Negative Curvature Detection:**  
- The implementation now detects negative curvature based on Algorithm 1 from the paper.  
- When negative curvature is detected:
- If the linesearch flag is enabled **and** it occurs on the first iteration, the algorithm returns `b`.
- Otherwise, it returns the last computed `r1`.
- **Linesearch Flag:**  
- …
> Implement Line Search with Negative Curvature Detection for MINRES Based on Liu et al. (2022)

- src/block_krylov_workspaces.jl
- src/cr.jl
- src/krylov_stats.jl
- src/krylov_workspaces.jl
- test/test_cr.jl
- test/test_stats.jl
The algorithm adapts its behavior upon detecting nonpositive curvature:
At iteration k = 0: Returns the right-hand side b with solver.npc_dir set to the preconditioned initial residual.
At iteration k > 0: Returns the solution from iteration k-1 with solver.npc_dir updated to the most recent residual.
This modification ensures that the CR algorithm can be effectively utilized within inexact Newton methods that employ a linesearch strategy.
> implementation Line Search with Negative Curvature Detection with direction for CR 
